- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello TAS TEAM"
    - name: Test Ping to 10.10.10.10 using default vrf
      net_ping:
        dest: 10.0.52.78      

